# Generated by Django 4.0.4 on 2022-05-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_delete_yuangong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
