# Generated by Django 4.0.4 on 2022-05-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='num',
            field=models.CharField(max_length=16, verbose_name='手机号'),
        ),
    ]
